(()=>{"use strict";
const gestori=Array.isArray(window.TOP_HOUSE_GESTORI)?window.TOP_HOUSE_GESTORI:[],regole=Array.isArray(window.TOP_HOUSE_REGOLE)?window.TOP_HOUSE_REGOLE:[],$=id=>document.getElementById(id);
const labels={segmento:{residenziale:"Residenziale",business:"Business",condominio:"Condominio"},commodity:{luce:"Luce",gas:"Gas",dual:"Luce e gas"},operazione:{switch:"Switch",voltura:"Voltura",subentro:"Subentro","nuova-attivazione":"Nuova attivazione","prima-attivazione":"Prima attivazione"},pagamento:{rid:"RID",bollettino:"Bollettino",indifferente:"Indifferente"},firma:{otp:"OTP",tablet:"Tablet",cartacea:"Cartacea",entrambe:"Qualsiasi modalità",indifferente:"Indifferente"},priorita:{semplice:"Procedura semplice",rapida:"Attivazione rapida","no-rid":"Pagamento senza RID",otp:"Firma OTP",compenso:"Migliore compenso",nessuna:"Nessuna preferenza"}};
const questions=[
{key:"segmento",label:"Tipologia cliente",title:"Per quale tipologia di cliente stai inserendo la pratica?",help:"La disponibilità può cambiare tra residenziale, business e condominio.",icon:"fa-user",options:[{value:"residenziale",title:"Residenziale",text:"Privato o abitazione",icon:"fa-house"},{value:"business",title:"Business",text:"Azienda, negozio o professionista",icon:"fa-briefcase"},{value:"condominio",title:"Condominio",text:"Fornitura intestata al condominio",icon:"fa-building"}]},
{key:"commodity",label:"Fornitura",title:"Quale fornitura serve al cliente?",help:"Puoi cercare una fornitura singola oppure luce e gas insieme.",icon:"fa-bolt",options:[{value:"luce",title:"Luce",text:"Solo energia elettrica",icon:"fa-bolt"},{value:"gas",title:"Gas",text:"Solo fornitura gas",icon:"fa-fire-flame-simple"},{value:"dual",title:"Luce e gas",text:"Entrambe le forniture",icon:"fa-layer-group"}]},
{key:"operazione",label:"Operazione",title:"Quale operazione devi effettuare?",help:"Se non sei sicuro, il sistema ti aiuta a riconoscerla.",icon:"fa-shuffle",options:[{value:"switch",title:"Switch",text:"Cambio gestore con contatore attivo",icon:"fa-right-left"},{value:"voltura",title:"Voltura",text:"Cambio intestatario con contatore attivo",icon:"fa-user-pen"},{value:"subentro",title:"Subentro",text:"Riattivazione di un contatore già utilizzato",icon:"fa-power-off"},{value:"nuova-attivazione",title:"Nuova attivazione",text:"Il contatore non è ancora presente",icon:"fa-plug-circle-plus"},{value:"prima-attivazione",title:"Prima attivazione",text:"Contatore presente ma mai attivato",icon:"fa-circle-play"},{value:"non-so",title:"Non lo so",text:"Rispondi a tre domande guidate",icon:"fa-circle-question"}]},
{key:"pagamento",label:"Pagamento",title:"Il cliente è disponibile ad attivare il RID?",help:"La risposta può escludere i gestori che accettano soltanto l’addebito diretto.",icon:"fa-credit-card",options:[{value:"rid",title:"Sì, RID",text:"Addebito sul conto corrente",icon:"fa-building-columns"},{value:"bollettino",title:"No, bollettino",text:"Il cliente non vuole il RID",icon:"fa-receipt"},{value:"indifferente",title:"È indifferente",text:"Entrambe le modalità vanno bene",icon:"fa-arrows-left-right"}]},
{key:"firma",label:"Firma",title:"Come può firmare il cliente?",help:"Scegli la modalità realmente utilizzabile dal cliente.",icon:"fa-file-signature",options:[{value:"otp",title:"OTP",text:"Firma tramite codice ricevuto dal cliente",icon:"fa-mobile-screen-button"},{value:"tablet",title:"Tablet",text:"Firma assistita direttamente sul dispositivo",icon:"fa-tablet-screen-button"},{value:"cartacea",title:"Cartacea",text:"Contratto stampato e firmato",icon:"fa-pen-nib"},{value:"entrambe",title:"Qualsiasi modalità",text:"Il cliente può utilizzare qualunque firma disponibile",icon:"fa-layer-group"},{value:"indifferente",title:"È indifferente",text:"Nessuna preferenza di firma",icon:"fa-arrows-left-right"}]},
{key:"priorita",label:"Priorità",title:"Qual è la priorità principale per questa pratica?",help:"Questa scelta ordina i risultati, ma non esclude gestori compatibili.",icon:"fa-ranking-star",options:[{value:"semplice",title:"Procedura semplice",text:"Meno passaggi e meno vincoli",icon:"fa-wand-magic-sparkles"},{value:"rapida",title:"Attivazione rapida",text:"Preferisci tempi operativi più brevi",icon:"fa-stopwatch"},{value:"no-rid",title:"Pagamento senza RID",text:"Priorità ai gestori che accettano il bollettino",icon:"fa-receipt"},{value:"otp",title:"Firma OTP",text:"Priorità alla firma digitale",icon:"fa-mobile-screen-button"},{value:"compenso",title:"Migliore compenso",text:"Ordina in base al valore relativo del gettone",icon:"fa-euro-sign"},{value:"nessuna",title:"Nessuna preferenza",text:"Mostra prima la compatibilità generale",icon:"fa-equals"}]}
];
const state={step:0,answers:{},diagnostic:{contatorePresente:null,contatoreAttivo:null,intestatoCliente:null,maiAttivato:null}};
const el={intro:$("introScreen"),wizard:$("wizardScreen"),results:$("resultsScreen"),start:$("startButton"),previous:$("previousButton"),backBottom:$("backBottomButton"),next:$("nextButton"),restart:$("restartButton"),newSearch:$("newSearchButton"),editAnswers:$("editAnswersButton"),counter:$("stepCounter"),percent:$("progressPercent"),bar:$("progressBar"),icon:$("questionIcon"),label:$("questionLabel"),title:$("questionTitle"),help:$("questionHelp"),grid:$("answersGrid"),diagnostic:$("diagnosticArea"),summary:$("selectionSummary"),notice:$("configurationNotice"),list:$("resultsList"),excludedPanel:$("excludedPanel"),excludedList:$("excludedList"),resultsSubtitle:$("resultsSubtitle")};
function showScreen(s){el.intro.hidden=s!=="intro";el.wizard.hidden=s!=="wizard";el.results.hidden=s!=="results";window.scrollTo({top:0,behavior:"smooth"})}
function resetDiagnostic(){state.diagnostic={contatorePresente:null,contatoreAttivo:null,intestatoCliente:null,maiAttivato:null}}
function resetAll(){state.step=0;state.answers={};resetDiagnostic();showScreen("intro")}
function renderQuestion(){const q=questions[state.step],p=Math.round((state.step+1)/questions.length*100);el.counter.textContent=`Domanda ${state.step+1} di ${questions.length}`;el.percent.textContent=`${p}%`;el.bar.style.width=`${p}%`;el.icon.innerHTML=`<i class="fa-solid ${q.icon}"></i>`;el.label.textContent=q.label;el.title.textContent=q.title;el.help.textContent=q.help;el.grid.innerHTML=q.options.map(o=>`<button class="answer-option${state.answers[q.key]===o.value?" is-selected":""}" type="button" data-value="${o.value}"><span class="answer-icon"><i class="fa-solid ${o.icon}"></i></span><span class="answer-copy"><strong>${o.title}</strong><small>${o.text}</small></span></button>`).join("");el.grid.querySelectorAll(".answer-option").forEach(b=>b.addEventListener("click",()=>selectAnswer(q,b.dataset.value)));renderDiagnostic();updateNavigation()}
function selectAnswer(q,v){state.answers[q.key]=v;if(q.key==="operazione"){delete state.answers.operazioneRisolta;resetDiagnostic()}renderQuestion()}
function diagnosticBlock(t,k,opts){return `<h3 class="diagnostic-title">${t}</h3><div class="diagnostic-options">${opts.map(([v,l])=>`<button class="diagnostic-button" type="button" data-diagnostic-key="${k}" data-value="${v}">${l}</button>`).join("")}</div>`}
function diagnosticResult(t){return `<h3 class="diagnostic-title">Operazione riconosciuta</h3><p class="diagnostic-result"><i class="fa-solid fa-circle-check"></i> ${t}</p><button class="diagnostic-button" type="button" data-diagnostic-key="contatorePresente" data-value="">Ricomincia la verifica</button>`}
function renderDiagnostic(){const op=questions[state.step].key==="operazione",need=state.answers.operazione==="non-so";el.diagnostic.hidden=!(op&&need);if(!op||!need){el.diagnostic.innerHTML="";return}const d=state.diagnostic;let h="";if(d.contatorePresente===null)h=diagnosticBlock("Il contatore è già presente?","contatorePresente",[["si","Sì"],["no","No"]]);else if(d.contatorePresente==="no"){state.answers.operazioneRisolta="nuova-attivazione";h=diagnosticResult("L’operazione individuata è: Nuova attivazione")}else if(d.contatoreAttivo===null)h=diagnosticBlock("Il contatore è attualmente attivo?","contatoreAttivo",[["si","Sì"],["no","No"]]);else if(d.contatoreAttivo==="si"&&d.intestatoCliente===null)h=diagnosticBlock("L’utenza è già intestata al cliente?","intestatoCliente",[["si","Sì"],["no","No"]]);else if(d.contatoreAttivo==="si"){state.answers.operazioneRisolta=d.intestatoCliente==="si"?"switch":"voltura";h=diagnosticResult(`L’operazione individuata è: ${labels.operazione[state.answers.operazioneRisolta]}`)}else if(d.maiAttivato===null)h=diagnosticBlock("Il contatore è già stato utilizzato in passato?","maiAttivato",[["si","Sì"],["no","No"]]);else{state.answers.operazioneRisolta=d.maiAttivato==="si"?"subentro":"prima-attivazione";h=diagnosticResult(`L’operazione individuata è: ${labels.operazione[state.answers.operazioneRisolta]}`)}el.diagnostic.innerHTML=h;el.diagnostic.querySelectorAll("[data-diagnostic-key]").forEach(b=>b.addEventListener("click",()=>{const k=b.dataset.diagnosticKey,v=b.dataset.value;delete state.answers.operazioneRisolta;if(v===""){resetDiagnostic();renderQuestion();return}state.diagnostic[k]=v;if(k==="contatorePresente"){state.diagnostic.contatoreAttivo=null;state.diagnostic.intestatoCliente=null;state.diagnostic.maiAttivato=null}if(k==="contatoreAttivo"){state.diagnostic.intestatoCliente=null;state.diagnostic.maiAttivato=null}renderQuestion()}))}
function currentValid(){const q=questions[state.step],v=state.answers[q.key];return !!v&&(q.key!=="operazione"||v!=="non-so"||!!state.answers.operazioneRisolta)}
function updateNavigation(){el.previous.disabled=state.step===0;el.backBottom.style.visibility=state.step===0?"hidden":"visible";el.next.disabled=!currentValid();el.next.innerHTML=state.step===questions.length-1?`Mostra risultati <i class="fa-solid fa-wand-magic-sparkles"></i>`:`Continua <i class="fa-solid fa-arrow-right"></i>`}
function nextStep(){if(!currentValid())return;if(state.step<questions.length-1){state.step++;renderQuestion();window.scrollTo({top:0,behavior:"smooth"})}else{renderResults();showScreen("results")}}
function previousStep(){if(state.step===0)return;state.step--;renderQuestion()}
const resolvedOperation=()=>state.answers.operazione==="non-so"?state.answers.operazioneRisolta:state.answers.operazione,arrayHas=(a,v)=>Array.isArray(a)&&a.includes(v);
function commodityMatches(a,r){if(!Array.isArray(a))return false;return r!=="dual"?a.includes(r)||a.includes("dual"):a.includes("dual")||(a.includes("luce")&&a.includes("gas"))}
function compatibility(r){const x=[],op=resolvedOperation();if(!r||r.verificato!==true)x.push("Regola non verificata");if(!arrayHas(r.segmenti,state.answers.segmento))x.push("Tipologia cliente non ammessa");if(!commodityMatches(r.commodity,state.answers.commodity))x.push("Fornitura non ammessa");if(!arrayHas(r.operazioni,op))x.push("Operazione non disponibile");if(state.answers.pagamento!=="indifferente"&&!arrayHas(r.pagamenti,state.answers.pagamento))x.push(state.answers.pagamento==="bollettino"?"Bollettino non accettato":"RID non disponibile");if(!["indifferente","entrambe"].includes(state.answers.firma)&&!arrayHas(r.firme,state.answers.firma))x.push(`Firma ${labels.firma[state.answers.firma]} non disponibile`);return x}
function scoreRule(r){let s=Number(r.prioritaBase||0)+40-Math.min((r.condizioni||[]).length,3)*2;switch(state.answers.priorita){case"semplice":s+=Number(r.semplicita||0)*4;break;case"rapida":s+=Number(r.rapidita||0)*4;break;case"no-rid":s+=arrayHas(r.pagamenti,"bollettino")?15:0;break;case"otp":s+=arrayHas(r.firme,"otp")?15:0;break;case"compenso":s+=Number(r.valoreGettone||0)*4;break;default:s+=Number(r.semplicita||0)+Number(r.rapidita||0)}return s}
function renderSummary(){const op=resolvedOperation(),items=[["fa-user",labels.segmento[state.answers.segmento]],["fa-bolt",labels.commodity[state.answers.commodity]],["fa-shuffle",labels.operazione[op]],["fa-credit-card",labels.pagamento[state.answers.pagamento]],["fa-file-signature",labels.firma[state.answers.firma]],["fa-ranking-star",labels.priorita[state.answers.priorita]]];el.summary.innerHTML=items.map(([i,t])=>`<span class="summary-chip"><i class="fa-solid ${i}"></i>${t}</span>`).join("")}
function resultCard(item,i){const{rule:r,manager:m}=item,c=Array.isArray(r.condizioni)?r.condizioni:[],reason=c.length?`Compatibile con la pratica. Condizioni: ${c.join("; ")}.`:"Compatibile con tutte le condizioni selezionate.",firma=Array.isArray(r.firme)?r.firme.map(v=>labels.firma[v]||v).join(" / "):"",d=[r.partner?`Partner: ${r.partner}`:"",r.rid?`RID: ${r.rid}`:"",r.impattoGettone?`Gettone: ${r.impattoGettone}`:"",firma?`Firma: ${firma}`:"",r.storno?`Storno: ${r.storno}`:"",r.bollette?`Bollette: ${r.bollette}`:"",r.aggiornato?`Aggiornato: ${r.aggiornato}`:""].filter(Boolean);return `<article class="result-card${i===0?" is-best":""}"><div><span class="result-rank"><i class="fa-solid ${i===0?"fa-crown":"fa-circle-check"}"></i>${i===0?"Gestore consigliato":"Alternativa compatibile"}</span><div class="result-heading"><h2>${m.nome}</h2><span class="status-badge">${c.length?"Con condizioni":"Compatibile"}</span></div><p class="result-reason">${reason}</p><div class="result-details">${d.map(v=>`<span class="detail-chip">${v}</span>`).join("")}</div></div><div class="result-actions"><a class="manager-link" href="${m.pagina}">Apri ${m.nome}<i class="fa-solid fa-arrow-right"></i></a>${m.procedura?`<a class="procedure-link" href="${m.procedura}">Procedura<i class="fa-solid fa-file-lines"></i></a>`:""}</div></article>`}
function renderResults(){const configured=regole.filter(r=>r&&r.verificato===true),ok=[],ko=[];configured.forEach(r=>{const m=gestori.find(g=>g.nome===r.gestore);if(!m)return;const reasons=compatibility(r);reasons.length?ko.push({rule:r,manager:m,reasons}):ok.push({rule:r,manager:m,score:scoreRule(r)})});ok.sort((a,b)=>b.score-a.score||a.manager.nome.localeCompare(b.manager.nome,"it"));renderSummary();el.notice.hidden=configured.length>0;el.list.innerHTML=ok.map(resultCard).join("");el.resultsSubtitle.textContent=!configured.length?"Il percorso è pronto; mancano soltanto le condizioni commerciali verificate.":!ok.length?"Nessun gestore configurato rispetta tutte le condizioni selezionate.":`${ok.length} ${ok.length===1?"gestore compatibile trovato":"gestori compatibili trovati"}.`;el.excludedPanel.hidden=!ko.length;el.excludedList.innerHTML=ko.map(x=>`<div class="excluded-row"><strong>${x.manager.nome}</strong><span>${x.reasons.join(" · ")}</span></div>`).join("")}
el.start.addEventListener("click",()=>{showScreen("wizard");renderQuestion()});el.next.addEventListener("click",nextStep);el.previous.addEventListener("click",previousStep);el.backBottom.addEventListener("click",previousStep);el.restart.addEventListener("click",resetAll);el.newSearch.addEventListener("click",resetAll);el.editAnswers.addEventListener("click",()=>{state.step=0;showScreen("wizard");renderQuestion()});document.addEventListener("keydown",e=>{if(el.wizard.hidden)return;if(e.key==="Enter"&&!el.next.disabled)nextStep();if(e.key==="Escape"&&state.step>0)previousStep()});
})();
